---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - "conda-forge::python=3.14.0"
  - "bioconda::bx-python=0.12.0"
